title: Merp4
description: A personal site showcasing my portfolio, documentation, and blog.
remote_theme: pages-themes/slate
plugins:
  - jekyll-remote-theme
markdown: kramdown
permalink: pretty
future: false
show_drafts: false
