title: Merp4
description: Personal portfolio, documentation, and technical blog built with Jekyll on GitHub Pages.
remote_theme: pages-themes/slate
plugins:
  - jekyll-remote-theme
markdown: kramdown
permalink: pretty
future: false
show_drafts: false
